### PR TITLE
Documents

### PR DESCRIPTION
**Pull request by MichelRiff**
# Pull Request Template

## Title
[Provide a succinct and descriptive title for the pull request, e.g., "Improve caching mechanism for API calls"]

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [x] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
[Provide a detailed explanation of the changes you have made. Include the reasons behind these changes and any relevant context. Link any related issues.]

## Testing
[Detail the testing you have performed to ensure that these changes function as intended. Include information about any added tests.]

## Impact
[Discuss the impact of your changes on the project. This might include effects on performance, new dependencies, or changes in behaviour.]

## Additional Information
[Any additional information that reviewers should be aware of.]

## Checklist
- [ ] My code adheres to the coding and style guidelines of the project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by CamilleGayat — APPROVED** [review]

**Review by AlexisLasselin — CHANGES_REQUESTED** [review]
I won't approve the pull request until the merging conflicts regarding the following documents:

Conflicting files
Specification/Technical/TechnicalSpecification.md
TestPlan/TestPlan.md
UserManual/User Manual Update.md
UserManual/User Manual.pdf

is solved.

Furthermore, I'll ask you to complete the pull request template. We must follow the rules, and it's the same for everyone, you're not exempted.

Denied

**Comment by CamilleGayat** [comment]
Conflicts that must be resolved

**Comment by MichelRiff** [comment]
# Pull Request Template

## Title
Merging Technical Specification

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [x] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
Document about all the technical aspect of this project.

## Testing
Reviewed by the Q&A.

## Impact
Explaining how the project work and how is it build to guide the team project.

## Additional Information
Nothing to add.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings

**Review by AlexisLasselin — APPROVED** [review]
Although it seems that some of us are having trouble handling a pull request, the result is that it should now be fine for the main branch.
However, you should be aware that if an error occurs again on another pull request, your skills will clearly be called into question.
Both for the person who creates the pull request and the person who approves it without realizing that there are conflicts on this PR.

You're lucky enough to be able to work together in the same room, so explain to me how you didn't manage to resolve the conflicts on your own, and whether it was via remote and asynchronous management that the problems were realized and resolved after almost 36 hours.

I hope you'll do better next time,

Pull request approved.

approved

**Pull request merged**
